### ISSUE TITLE
maven依赖下载不到

### ISSUE THREAD

**Issue by LazyBoom** [ToQuery/CleverWeb#8]
大佬你好，我想本地启动CleverWeb  发现pom里配置了很多你自己的依赖，这些依赖我拉不下来，请问该怎么处理？谢谢

**Comment by ToQuery** [comment]
能否提供下未找到的依赖，可以通过命令 `mvn clean install -X -DskipTests` 获取详细信息

**Comment by LazyBoom** [comment]
使用 mvn clean install -X -DskipTests 之后可以了  谢谢
